jasypt:
  encryptor:
    bean: jasyptEncryptor
---
spring:
  config.activate.on-profile: local
token:
  secret: secretsecretsecretsecretsecretsecretsecretsecret
  duration: 1d
---
spring:
  config.activate.on-profile: dev
token:
  secret: ENC(eR+9fFJXsZAbZe016bEdE4km26cFFRahw2OMW/mvvh9Ja106gD/zqZTW6c9s8+xCGaOKwyPyhKWxIQio67w8OgFQRIZxgwbHFzIYVvfzmE6XKWa8u1GUe5w3iqEkVl6JRBS902oMMCc=)
  duration: 1d
---
spring:
  config.activate.on-profile: prod
token:
  secret: ENC(qtaJWd0HLtgq7+tXwF5Tz8x4sgZbZ+nZOcSbNO90gTldwEu6T+7sWKSK+zdlmWSAeucE7BW2Lr0oOR9Y4hIEXwt2pwsN/l2meJIBNXaCtvVUhatB/OWUWS02SjLapEnS95jw0VGpdWg=)
  duration: 1d
