spring:
  config.activate.on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
      password:

---
spring:
  config.activate.on-profile: dev
  data:
    redis:
      host: ec2-43-200-209-158.ap-northeast-2.compute.amazonaws.com
      port: 6379
      password: ENC(SxyeWbUJxS2juCdWHl3bjkcN+kiNhWVvCbnW1LB7vLQ=)

---
springS:
  config.activate.on-profile: prod
