spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/realworld
    username : sms
    password : qwerty123

---
spring:
  config.activate.on-profile: dev
  datasource:
    url: ENC(fN2bMJC0n32LmeZTtrOa7es7hNEYyJuLCe7WE8AernItO278thDkJI8y9fWpmrpspCzB+IDl0TtEMEV+djTn3HmMYBsNlPHDN6FDZa78QJNsSceCVLcIY9toHBUoJzM/gzpYwHg1mHs=)
    username: ENC(KK/rEJ9Yc+3FWZ02POvb1w==)
    password: ENC(ab18+wsT1dg62d2Vsmv7bJLrJpw2EquM)

---
spring:
  config.activate.on-profile: prod
