spring:
  jpa:
    hibernate:
      ddl-auto: validate

---
spring:
  config.activate.on-profile: local
  jpa:
    generate-ddl: true
  sql:
    init:
      mode: always
      continue-on-error: true
      schema-locations: classpath:db/init_schema.sql

---
spring:
  config.activate.on-profile: dev

---
spring:
  config.activate.on-profile: prod
