spring:
  config.activate.on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
      password:

---
spring:
  config.activate.on-profile: dev
  data:
    redis:
      host: ENC(aQsUNBJZTf1X86HrfJuOHBNnMHCXNedsegdDnQ0O0yhIhtYFuiS3dV+hdHpryZVt78M6EINbMWY9uegUVR4G2A==)
      port: 6379
      password: ENC(SxyeWbUJxS2juCdWHl3bjkcN+kiNhWVvCbnW1LB7vLQ=)

---
spring:
  config.activate.on-profile: prod
